name: bookclub
description: Aplicativo BookCLUB - Login e Cadastro de Usuários
publish_to: 'none' # não será publicado no pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Permite salvar dados localmente (ex: lembre-me)
  shared_preferences: ^2.2.3

  # Ícones e Material 3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Caso use imagens (ex: ícones do Figma)
  assets:
    - assets/images/

  # Fonte Roboto (como no Figma)
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
